//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.08 at 10:31:00 PM CEST 
//


package org.freedesktop.appstream.appdata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}translation" minOccurs="0"/>
 *         &lt;element ref="{}name" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}summary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}icon" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}categories"/>
 *         &lt;element ref="{}keywords"/>
 *         &lt;element ref="{}kudos"/>
 *         &lt;element ref="{}project_license"/>
 *         &lt;element ref="{}url" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}project_group"/>
 *         &lt;element ref="{}compulsory_for_desktop" minOccurs="0"/>
 *         &lt;element ref="{}screenshots"/>
 *         &lt;element ref="{}languages" minOccurs="0"/>
 *         &lt;element ref="{}bundle"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "translation",
    "name",
    "summary",
    "description",
    "icon",
    "categories",
    "keywords",
    "kudos",
    "projectLicense",
    "url",
    "projectGroup",
    "compulsoryForDesktop",
    "screenshots",
    "languages",
    "bundle"
})
@XmlRootElement(name = "component")
public class Component {

    @XmlElement(required = true)
    protected String id;
    protected Translation translation;
    protected List<Name> name;
    protected List<Summary> summary;
    protected List<Description> description;
    protected List<Icon> icon;
    @XmlElement(required = true)
    protected Categories categories;
    @XmlElement(required = true)
    protected Keywords keywords;
    @XmlElement(required = true)
    protected Kudos kudos;
    @XmlElement(name = "project_license", required = true)
    protected String projectLicense;
    protected List<Url> url;
    @XmlElement(name = "project_group", required = true)
    protected String projectGroup;
    @XmlElement(name = "compulsory_for_desktop")
    protected String compulsoryForDesktop;
    @XmlElement(required = true)
    protected Screenshots screenshots;
    protected Languages languages;
    @XmlElement(required = true)
    protected Bundle bundle;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the translation property.
     * 
     * @return
     *     possible object is
     *     {@link Translation }
     *     
     */
    public Translation getTranslation() {
        return translation;
    }

    /**
     * Sets the value of the translation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Translation }
     *     
     */
    public void setTranslation(Translation value) {
        this.translation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Name }
     * 
     * 
     */
    public List<Name> getName() {
        if (name == null) {
            name = new ArrayList<Name>();
        }
        return this.name;
    }

    /**
     * Gets the value of the summary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Summary }
     * 
     * 
     */
    public List<Summary> getSummary() {
        if (summary == null) {
            summary = new ArrayList<Summary>();
        }
        return this.summary;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the icon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Icon }
     * 
     * 
     */
    public List<Icon> getIcon() {
        if (icon == null) {
            icon = new ArrayList<Icon>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Categories }
     *     
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Categories }
     *     
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Keywords }
     *     
     */
    public Keywords getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *     
     */
    public void setKeywords(Keywords value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the kudos property.
     * 
     * @return
     *     possible object is
     *     {@link Kudos }
     *     
     */
    public Kudos getKudos() {
        return kudos;
    }

    /**
     * Sets the value of the kudos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kudos }
     *     
     */
    public void setKudos(Kudos value) {
        this.kudos = value;
    }

    /**
     * Gets the value of the projectLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectLicense() {
        return projectLicense;
    }

    /**
     * Sets the value of the projectLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectLicense(String value) {
        this.projectLicense = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Url }
     * 
     * 
     */
    public List<Url> getUrl() {
        if (url == null) {
            url = new ArrayList<Url>();
        }
        return this.url;
    }

    /**
     * Gets the value of the projectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectGroup() {
        return projectGroup;
    }

    /**
     * Sets the value of the projectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectGroup(String value) {
        this.projectGroup = value;
    }

    /**
     * Gets the value of the compulsoryForDesktop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompulsoryForDesktop() {
        return compulsoryForDesktop;
    }

    /**
     * Sets the value of the compulsoryForDesktop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompulsoryForDesktop(String value) {
        this.compulsoryForDesktop = value;
    }

    /**
     * Gets the value of the screenshots property.
     * 
     * @return
     *     possible object is
     *     {@link Screenshots }
     *     
     */
    public Screenshots getScreenshots() {
        return screenshots;
    }

    /**
     * Sets the value of the screenshots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screenshots }
     *     
     */
    public void setScreenshots(Screenshots value) {
        this.screenshots = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setLanguages(Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link Bundle }
     *     
     */
    public Bundle getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bundle }
     *     
     */
    public void setBundle(Bundle value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
